server:
  port: 8081
spring:
  application:
    name: RoleConsumer02
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka

#Ribbon负载均衡策略
ROLEPROVIDER: #服务名称
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #随机策略

